Enforce checking of python package version.

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -14,6 +14,17 @@ jobs:
         uses: actions/setup-python@v3
         with:
           python-version: "3.11"
+      - name: Compare versions in setup.py and knowledge_storm/__init__.py
+        run: |
+          VERSION_SETUP=$(grep -oP '(?<=version=\").*(?=\")' setup.py)
+          VERSION_INIT=$(grep -oP '(?<=__version__ = \").*(?=\")' knowledge_storm/__init__.py)
+          echo "Version in setup.py: $VERSION_SETUP"
+          echo "Version in __init__.py: $VERSION_INIT"
+          if [ "$VERSION_SETUP" != "$VERSION_INIT" ]; then
+            echo "Error: Version mismatch between setup.py ($VERSION_SETUP) and knowledge_storm/__init__.py ($VERSION_INIT)"
+            exit 1
+          fi
+        shell: bash
       - name: Install dependencies
         run: python3 -m pip install setuptools wheel twine
       - name: Install dependencies
